import Icon1 from "../../assets/images/22north_Blog_1.jpg";
import Icon2 from "../../assets/images/22north_Blog_2.jpg";
import Icon3 from "../../assets/images/22north_Blog_3.jpg";
import Icon4 from "../../assets/images/22north_Blog_4.jpg";

const blogs = [
  {
    blogIcon: Icon1,
    blogIconAlt: "22north blogs - Startup Guidance",
    blogName: "How to stand out from the Crowd",
    blogId: "Guidance",
    blogSelected: false,
    blogPath: "/how-to-stand-out-from-the-crowd",
    blogDetails: [
      "“There are two ways of making yourself stand out from the crowd. One is by having a job, so big you can go home before the bell rings if you want to. The other is by finding; so much to do that you must stay after the others have gone. The one who enjoys the former once took advantage of the latter”                                        - Henry Ford",
      "One can do all kinds of things to get noticed, but very few of us make a lasting impression. But what if you get noticed in a crowded place of professionals as a real entrepreneur, the leader that you are? Well, there are some strategies that really work.",
      "Most entrepreneurs have a strong and unreflective urge or desire to act, and they are the most passionate people who live by the feelings. But those who understand and practice the art of discipline can channel those urges or desires into something of substance.",
      "Whether you’re in a face-to-face meeting or are communicating via email or letter, it’s essential you come across as original, to ensure you stand out from the crowd. Originality works magically be it your CV or job interview.",
      "To know yourself is an important element for an entrepreneur. Ask others about yourself and get to know your strength and weaknesses. Record your presentations and listen to them. After all, you yourself are your biggest critic.",
      "Always being on time, honoring your commitments and being prepared is the most important thing. Nothing is more powerful than an individual acting out of a well-developed consciousness.",
      "Be good at what you do, know who you are, have passion and communicate all this through a carefully balanced blend of physicality, personality, presence and inner confidence.",
      "It is seen, those people who are competent and capable can attract people who are looking to connect with someone.",
      "An entrepreneur needs to be the kind of person who responds and remembers to follow through on time. Most people neglect and do not follow up on time. Respond to emails, calls, requests, and inquiries at the earliest you can and that makes out a person who respects others and is accountable.",
      "When you truly envisage what you believe, you should not be afraid of obstacles. This confidence will automatically make you stand out from the rest.",
    ],
  },
  {
    blogIcon: Icon2,
    blogIconAlt: "22north blogs Funding",
    blogName: "Mistakes a Start-Up Should Avoid Doing",
    blogId: "Funding",
    blogSelected: false,
    blogPath: "/mistakes-a-start-up-should-avoid-doing",
    blogDetails: [
      "So, if you are starting a business, you’d surely like to tick off the below-mentioned checklists before taking the plunge.  After all, business is a complex venture that very few can pull off. Hence, there are certain common mistakes that one needs to avoid to see efforts come to fruition.",
      "Industry knowledge is not all that you need to know when starting a business. You may be a very good programmer but the most important part is to sell that software when it comes to business. So, first assess your target customers, barriers to entry, level of competition from both bigger and smaller players and the expansion potential of the market you are targeting. And if you are intending to hit a niche segment, the sky could be limit if successful.",
      "Hiring Should be Extremely Balanced. One should plan for balanced hiring. While trying to do everything yourself may hamper the quality of your products and services (and kind of impossible too), excessive hiring may also hurt your revenues and profitability. If a particular task can be accomplished by a part-time worker, no need to go for a full-time recruitment. So, getting your work done though freelancing and outsourcing can be a key to business success.",
      "Marketing is sometimes considered as trivial as well as costly by many entrepreneurs. In reality, it is extremely essential to make presence known to your target customers. Investing on marketing is always not a very expensive venture. If you are tight on budget in the initial days, at least try to market your products or services on social media channels like Twitter, Facebook and LinkedIn. Contacts and referrals may also help in accomplishing your marketing goal. ",
      "A startup accelerator is fixed-term, cohort-based programs, that help start-ups in their early days by mentoring, training and arranging for seed funding. Accelerators can be either privately or publicly funded and cover a wide range of industries. Per Wikipedia, unlike business incubators, the application process for seed accelerators is open to all, though these are very competitive.",
      "Big corporations are often behind this kind of accelerator program. Notably, e-Commerce giant Amazon recently said that it is partnering with Startup India to launch an accelerator program to help early-stage Indian consumer product start-ups to access international markets. This is part of the Amazon’s Global Selling Propel programme.",
      "Valuation is important for every business; more so for a start-up as it often needs venture capital funding to grow. Startups need to undergo different rounds of fundraising, which are pre-seed, seed and series rounds. Here is where the valuation comes into play.",
      "Factors such as credentials as well as the track records of the entrepreneur, business traction, revenues and recent acquisitions on the market of a similar kind of startup will help in ascertaining the value of your company. A sound business plan is also necessary in determining the valuation. Note that one should not over-or-underestimate challenges and be prepare for the worst-case scenario.",
      "Intellectual Property (IP) assets are extremely common and important for tech start-ups. This is one area that investors and the purchaser pays generously for. It means any inventions, ideas and products conceived or created by the startup, will be owned by the creator only. Such exclusivity may help you crack a great deal when you look for funding.",
      "Things always don’t go as you plan. Even a super-seasoned industrialist like Ratan Tata could not experience full success with his dream project Tata Moto’s Nano. The low-cost ‘people’s car first faced cost issues and then hardly saw solid demand in domestic market. So, one could imagine that a startup entrepreneur may have to adapt with sudden changes and must have a plan B for his business if plan A goes wrong.",
      "If you are starting a business with a partner, it is wise to have a 51/49 partnership agreement rather than 50/50. This way you can share costs, responsibilities and diversify risks while avoiding confusions over who will take the call if any of the partners disagree at some point.",
      "Don’t be afraid if you do not experience enough success at the first go. Failures happen and one should learn from the failure to keep going. As Winston Churchill said “success is not final, failure is not fatal: it is the courage to continue that counts.",
      "Sources:",
      "https://www.forbes.com/quotes/author/henry-h-buckley/",
      "https://www.businessnewsdaily.com/7398-startup-mistakes-to-avoid.html",
      "https://www.thebalancesmb.com/small-business-startup-mistakes-2951860",
      "https://www.educba.com/business-startup-mistakes-to-avoid",
      "https://onix-systems.medium.com/5-mistakes-startups-should-avoid-dd84c1df8b24",
      "https://yourstory.com/mystory/10-mistakes-every-startups-should-avoid-to-be-succ",
      "https://www.forbes.com/sites/ekaterinawalter/2013/12/30/30-powerful-quotes-on-failure/?sh=780071a724bd",
      "https://www.thebalancesmb.com/top-mistakes-when-starting-a-business-2948567",
      "https://startupvalue.io/",
      "https://corporatefinanceinstitute.com/resources/knowledge/valuation/startup-valuation-methods/",
    ],
  },
  {
    blogIcon: Icon3,
    blogIconAlt: "22north blogs Office Space",
    blogName: "Insights to Grow Your Business",
    blogId: "OfficeSpace",
    blogSelected: false,
    blogPath: "/insights-to-grow-your-business",
    blogDetails: [
      "Starting a business can be scary, because huge risks are involved in it. But the sheer thought of owning a business and see it growing is a thrilling experience. However, there’s a big difference between starting a business and being able to turn it into a long-term success. So, what are the judicious ways to grow a startup? Let’s delve a little deeper.",
      "1. Prudent Market Research & Usage of Analytics",
      "To start and grow a business, consistent research on the industry and the market is necessary. Studying customer needs, analyzing industry trends, as well as market size of the field you are entering, expansion potential, customers’ feedback and usage of technology and analytics, are some of the key areas you need to hone in on.",
      "Note that, adoption of technology will help you survive on financial matter over the long run. Likewise, if your start-up is dealing with lots of data, then usage of business analytics from the budding phase could prove to be fruitful.",
      "Business Analytics is a process of collecting and studying a vast pool of data and drawing inferences from it. Today, businesses, across the sizes, are deploying analytics tools to determine how data can be put to use to resolve complex problems and increase the perfection of a model as well as boost revenues.",
      "2. Cut Costs Via Flexible Workspace",
      "The demand for flexible workspace has been rising steadily. Since 2013, the use of shared workspaces has doubled globally, and they now make up about one third of all the flexible working offices, per an article published on techspace.com. The shared workspace can be rented even for a few hours. Your business can use the space exactly for what it wants to and doesn’t have to pay for what it doesn’t need.",
      "There is an option for work-from-home too as this option will help the entrepreneur access a talent pool across the country or globe. Both ways of working will save the business owner costs of buying or renting office space over the long term, which is pretty costly in big cities.",
      "3. Mindful Marketing Strategy",
      "Marketing is extremely important for a new business; otherwise, how would people know about your presence? So, first identify your unique selling proposition (USP) or the factor that makes you different from your competitors.",
      "These USPs could be special skills or knowledge that you or your partners have, your credentials, the highpoints of your business and the quote price for your products and services that may appear lucrative to your clients.",
      "After doing this, start marketing your USP. If you are tight on budget in the initial days, at least try to market your products or services on social media channels like Twitter, Facebook and LinkedIn. Contacts and referrals may also help in accomplishing your marketing goal. ",
      "4. Brand-Building Is Crucial",
      "A brand building is necessary. A well-expressed and emotionally-connected tagline sometimes work wonder in winning over audiences’ hearts. Remember, your target should be to turn a one-time visitor on say a Facebook page into a subscriber.",
      "Per an article published on eu-startups, email newsletter subscribers often prove to more valuable than social media followers, as you can reach out to them anytime. If a startup’s Facebook page can reach 5% of audiences, an email delivered to the inbox of all its contacts should definitely fetch way more businesses.",
      "5. Try to Make a Big Venture From a Bunch of Small Bets",
      "In the budding phase of your entrepreneurial journey, it is hard to make big bets seamlessly. No worry, it is not required to crack one big deal, rather lots of consistent small deals will grow your business. A few models say that adopting a lean startup methodology for developing businesses is a good idea as it always has a market.",
      "Notably, this methodology supports developing products and services for which consumers have already expressed their interests. This methodology looks to minimize product development cycles and discover fast if a planned business model is feasible.",
    ],
  },
  {
    blogIcon: Icon4,
    blogIconAlt: "22north blogs Business Development",
    blogName: "Understanding the Potential of Tech Start-Ups in India",
    blogId: "BusinessDevelopment",
    blogSelected: false,
    blogPath: "/understanding-the-potential-of-tech-start-ups-in-india",
    blogDetails: [
      "The technology sector has registered an exponential growth over the past decade with social media, remote communications, cloud computing, cyber security, e-commerce and robotics taking the spotlight. The COVID-19 pandemic and the resultant social distancing norms have augmented the utility of digitization even more. Per NASSCOM1, mega global tech trends are currently associated with Augmented Reality, Smart Cards, Urbanization Solution for Public, Smart Security, Smart is the New Green, Smart City Initiative India, Social Trends – Gen Y Geo Socialization, Automation, Future of Mobility and so on. While big tech behemoths have a strong foothold in the above-said areas, start-ups too are well-positioned to take the solid advantage of this boom.",
      "Per NASSCOM1, mega global tech trends are currently associated with Augmented Reality, Smart Cards, Urbanization Solution for Public, Smart Security, Smart is the New Green, Smart City Initiative India, Social Trends – Gen Y Geo Socialization, Automation, Future of Mobility and so on. While big tech behemoths have a strong foothold in the above-said areas, start-ups too are well-positioned to take the solid advantage of this boom.",
      "Notably, the global startup economy is currently valued at about $3 trillion, according to startupgenome.com2. Within this, India has the third largest startup economy, which is likely to record a steady annual growth of 12-15%, per startupindia.gov.in.",
      "With more than 1600 tech start-ups added in 2020, the Indian tech start-up space has been clocking a steady year-over-year growth rate of 8-10%, per an article from economictimes4. In India, about 14% of total investments in 2020 were in deep-tech start-ups, up from 11% in 2019. About 87% of all deep-tech investments were in AI/ML in 2020. Debjani Ghosh, President of NASSCOM recently indicated that “2021 promises to be a positive year for Indian tech start-ups – marching steadily towards $1Tn digital economy goal.”",
      "Pari Natarajan, CEO, Zinnov, said that, “2020 saw start-ups increasingly leveraging and piggybacking on the foundational infrastructure that the government has in place – the India Stack, UPI infrastructure, GST norms, FASTag, etc. – that offers up a unified set of layers with contactless and presence-less digital economy truly coming into its own.”",
      "Though pandemic kept total number of start-up deals subdued in 2020, seed-stage investments have been in fine fettle and remained almost same as 2019 levels in India. Early and Late-stage investments are also recovering steadily right now.",
      "Sectors like EdTech, BFSI, AgriTech, Gaming have been garnering first-time funding steadily, up from 29% in 2019 to 42% in 2020, per the economic times article. Further, 28-30% tech start-ups are also having foreign market expansion plans. The upbeat figure underscores the sheer potential of the Indian tech start-up space in the near term.",
      "Source:",
      "1. https://nasscom.in/knowledge-centre/facts-figures",
      "2. https://startupgenome.com/article/state-of-the-global-startup-economy",
      "3. https://www.startupindia.gov.in/content/sih/en/international/go-to-market-guide/indian-startup-ecosystem.html",
      "4.  https://cio.economictimes.indiatimes.com/news/next-gen-technologies/deep-tech-adoption-driving-growth-for-indias-tech-startups-in-2021-report/80152836",
    ],
  },
];

export default blogs;
