export const homeObjAbout = {
  id: "about",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "About Us",
  topLine: "",
  descriptions: [
    "22 North is a Silicon Valley-based Incubator Company with the aim of helping young Indian professionals realize their entrepreneurial dreams.",
    "There has been an increase in the number of deep-tech start-ups, with over 18% of startups being involved in high-end engineering. These are primarily initiatives taken by young entrepreneurs who are looking to replicate successful Silicon Valley business models.",
    "For us at 22 North, our goal is to help and support such young entrepreneurs who have a clear vision for their technology idea. We will provide you with the initial support for funding, infrastructure, corporate guidance, business development, and due diligence. You will own your startup, we will be your partner.",
    "You have to dream – we would be there to see your dream coming to fruition. We expect you to put your future and your family’s future on the line for success. We consider that to be an essential ingredient for success.",
  ],
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../assets/images/22north_about.jpg").default,
  alt: "BoxStep What do we do",
  dark: true,
  dark2: false,
  primary: true,
  // backgroundImage: require("../../assets/images/InfoContainer.jpeg").default,
};

export const homeObjTeam = {
  id: "team",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "Management",
  topLine: "22 North is headed by Buddhadeb Biswas (Bud Biswas).",
  descriptions: [
    "Bud Biswas is the Founder and CEO of 22North. Backed by over 30 years of industry experience, in the field of networking and communication, his knowledge of business is profound. It is his track record of transforming small Start up firms into profitable business units, that had prompted him to start 22 North. He founded Digital Technology, which in the year 2000 was acquired by Agilent Technologies. He was also one of the founding partners of Network Software (a network consulting company) and, CCS (an embedded software company). After this Bud founded Polaris Networks Inc (a 4G/5G networking company) in 2003. In 2020 Polaris was acquired by a US fortune 100 company.",
    "It is no wonder that he knows exactly what works and what doesn’t, as business models. Ably supported by professionals from different business fields, 22 North has the perfect blend of experience and young professional inputs to propel ideas to business realities. By choosing to trust Team 22North, you are choosing to trust partnership that would propel you to success. If you have a dream, we have the right solution to reach to a desired destination!",
  ],
  buttonLabel: "Get Started",
  imgStart: true,
  img: require("../../assets/images/22north_team.svg").default,
  alt: "BoxStep Who Are We",
  dark: true,
  dark2: false,
  primary: true,
  // backgroundImage: require("../../assets/images/background.jpg").default,
};
