export const homeObjAbout = {
  id: "about",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "About Us",
  topLine: "",
  descriptions: [
    "22North (TTN) is a Silicon Valley-based Incubator Company with the aim of helping young Indian professionals realize their entrepreneurial dreams by providing seed funding. With a substantial increase in the number of deep-tech start ups, most young entrepreneurs are looking to secure angel funding in order to build and empower their dreams.",
    "Team TTN is looking to do just this - help young companies get started, build a strong foundation and grow. By investing in young companies, the idea is not just to provide funding; the goal is to provide all round strategic guidance including business development support, infrastructure as well as product and/or market due diligence.",
    "What we are looking for is an entrepreneur's belief in herself and her dream, her willingness to pursue this dream with everything at stake. Chase your Passion & Create Opportunities.",
  ],
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../assets/images/22north_about.jpg").default,
  alt: "22north What do we do",
  dark: true,
  dark2: false,
  primary: true,
  // backgroundImage: require("../../assets/images/InfoContainer.jpeg").default,
};

export const homeObjTeam = {
  id: "team",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "Team",
  topLine: "22 North (TTN) is headed by Buddhadeb Biswas (Bud Biswas).",
  descriptions: [
    "Backed by over 30 years of industry experience in the field of networking and communication, Bud's knowledge of business is profound. It is his track record of transforming small start up firms into profitable business units, that prompted him to start 22 North. He founded Digital Technology, which in the year 2000 was acquired by Agilent Technologies. He was also one of the founding partners of Network Software (a network consulting company) and, CCS (an embedded software company). After this Bud founded Polaris Networks Inc (a 4G/5G networking company) in 2003. In 2020 Polaris was acquired by a US fortune 100 company.",
    "Ably supported by professionals from different business fields, Team TTN is the perfect blend of experience and young professional inputs to propel ideas to business realities. If you have a dream, Team TTN will empower you to realize your vision.",
  ],
  buttonLabel: "Get Started",
  imgStart: true,
  img: require("../../assets/images/22north_team_final.jpg").default,
  alt: "22north Who Are We",
  dark: true,
  dark2: false,
  primary: true,
  // backgroundImage: require("../../assets/images/background.jpg").default,
};

export const homeObjFunding = {
  id: "funding",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "Funding",
  topLine: "Get Selected and Grow with Us",
  descriptions: [
    "22North is keen to invest in early stage businesses which have the potential to create value. The members of the network are leaders in the Entrepreneurial ecoSystem, with strong operational experience as CEOs and/or a background of creating new and successful ventures. They share a passion to create value for start up ventures.",
    "So, if you have an entrepreneurial acumen and a promising technical idea, TTN is the right place for you. Not only will you be assisted with funding, you will get access to a team who will nurture your idea into an established business.",
    "If you are looking for an investment partner and strategic guidance, please send in a presentation consisting of 5-7 Slides (with a max file size of 5MB) covering the basic aspects of the proposition and the business plan. The presentation should comprise of your academic qualification, your business and growth plan along with a glimpse of your technical idea. You can send in the presentation to info@22north.us. ",
  ],
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../assets/images/Register.jpeg").default,
  alt: "22north Funding",
  dark: true,
  dark2: false,
  primary: true,
};

export const homeObjResearch = {
  id: "rnd",
  lightBg: true,
  darkText: true,
  lightText: false,
  lightTextDesc: false,
  headLine: "R&D",
  topLine: "Technology Research",
  descriptions: [
    "We are in stealth mode about the Research and Development (R&D) in some cutting edge technology domain.",
    "  ",
    "   ",
  ],
  buttonLabel: "Get Started",
  imgStart: true,
  img: require("../../assets/images/22north_technology_research.svg").default,
  alt: "22north Funding",
  dark: true,
  dark2: false,
  primary: true,
};
